name: medicalreader
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.7
  file_picker: ^12.0.0-beta.5
  path_provider: ^2.1.4
  ffi: ^2.2.0
  archive: 4.0.9
  xml: ^7.0.1
  flutter_inappwebview: ^6.1.5
  path: any
  markdown: ^7.3.1
  flutter_markdown_plus: ^1.0.12
  record: ^7.1.1
  camera: ^0.12.0+2
  camera_android: ^0.10.11
  camera_desktop: ^1.2.1
  flutter_html: ^3.0.0
  just_audio: ^0.10.4
  pdfx: ^2.11.0
  pdf: ^3.11.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/book_templates/
    - assets/branding/
    - assets/ui/

flutter_launcher_icons:
  android: true
  image_path: "assets/branding/favicon.ico"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/branding/favicon.ico"
  windows:
    generate: true
    image_path: "assets/branding/favicon.ico"
    icon_size: 256
