[target.aarch64-linux-android]
linker = "D:/Android/Sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android21-clang.cmd"
ar = "D:/Android/Sdk/ndk/28.2.13676358/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
rustflags = [
    "-C",
    "link-arg=-lc++_shared",
    "-C",
    "link-arg=-Wl,--as-needed",
    "-C",
    "link-arg=-stdlib=libc++",
]
